# -*- coding: utf-8 -*-
"""Group1_ Unit1Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hsejg_cB9W8d2L1KcxP3EZVn9T9LOlhu

# Person 1 - Stadium & Match Information
"""

# Stadium data
stadiums = {
    "1": {
        "name": "King Salman Stadium",
        "transport": "King Salman Stadium Station - Line 7",
        "area": "North Riyadh"
    },
    "2": {
        "name": "King Fahad Sports City",
        "transport": "King Fahad Sport City Station - Red Line",
        "area": "East Riyadh"
    },
    "3": {
        "name": "Alinma Stadium",
        "transport": "Best reached by car or ride-hailing",
        "area": "Jeddah"
    },
    "4": {
        "name": "Aramco Stadium",
        "transport": "Best reached by car or ride-hailing",
        "area": "Khobar"
    }
}


# Match data
matches = {
    "1": {
        "stadium": "King Salman Stadium",
        "match": "Saudi Arabia vs Argentina",
        "date": "June 15, 2034",
        "time": "3:00 PM"
    },
    "2": {
        "stadium": "King Salman Stadium",
        "match": "Brazil vs England",
        "date": "June 20, 2034",
        "time": "7:00 PM"
    },
    "3": {
        "stadium": "King Fahad Sports City",
        "match": "France vs Spain",
        "date": "June 16, 2034",
        "time": "3:00 PM"
    },
    "4": {
        "stadium": "King Fahad Sports City",
        "match": "Germany vs Italy",
        "date": "June 18, 2034",
        "time": "7:00 PM"
    },
    "5": {
        "stadium": "Alinma Stadium",
        "match": "Portugal vs Netherlands",
        "date": "June 19, 2034",
        "time": "5:00 PM"
    },
    "6": {
    "stadium": "Aramco Stadium",
    "match": "Argentina vs France",
    "date": "June 20, 2034",
    "time": "8:00 PM"
    }
}


# Choose stadium
def choose_stadium(stadiums):
    print("\n Choose your stadium:")
    print("1. King Salman Stadium")
    print("2. King Fahad Sports City")
    print("3. Alinma Stadium")
    print("4. Aramco Stadium")

    choice = input("Enter your choice: ")

    while choice not in stadiums:
        print(" Invalid choice. Please choose 1, 2, 3, or 4.")
        choice = input("Enter your choice: ")

    return stadiums[choice]


# Choose match time
def choose_match(matches, stadium):
    print("\n Choose your match time:")

    available_matches = {}

    for key in matches:
        if matches[key]["stadium"] == stadium["name"]:
            available_matches[key] = matches[key]

    for key in available_matches:
        print(
            key + ". " +
            available_matches[key]["date"] +
            " - " +
            available_matches[key]["time"]
        )

    choice = input("Enter your choice: ")

    while choice not in available_matches:
        print(" Invalid choice. Please choose from the available matches.")
        choice = input("Enter your choice: ")

    return available_matches[choice]


# Main function
def get_match_information(stadiums, matches):
    stadium = choose_stadium(stadiums)
    match = choose_match(matches, stadium)

    print("\n YOUR MATCH INFORMATION")

    print("Stadium:", stadium["name"])
    print("Match:", match["match"])
    print("Match Date:", match["date"])
    print("Match Time:", match["time"])
    print("Getting There:", stadium["transport"])
    print("Area:", stadium["area"])

    return stadium, match


"""# Person 2 - cafes and restaurants"""

"""
RENAD | My task was to show cafes or restaurants based on the selected stadium.
The stadium and match information come from Person 1.
The user chooses whether they want a cafe or restaurant,
then gets suitable options based on the selected stadium.

The food recommendations are returned to the final plan,
so they are printed only once in the final output.
"""


# Food recommendation based on the selected stadium

def food_recommendation(stadium, match):

    print("\nWhat would you like?")
    print("1. Cafe")
    print("2. Restaurant")

    while True:
        food_type = input("Enter the number: ")

        if food_type in ["1", "2"]:
            break

        print("Please enter only 1 or 2.")

    if stadium["name"] == "King Salman Stadium":

        if food_type == "1":
            return choice_food_king_salman_cafe()

        elif food_type == "2":
            return choice_food_king_salman_restaurant()


    elif stadium["name"] == "King Fahad Sports City":

        if food_type == "1":
            return choice_food_king_fahd_cafe()

        elif food_type == "2":
            return choice_food_king_fahd_restaurant()


    elif stadium["name"] == "Alinma Stadium":

        if food_type == "1":
            return choice_food_alinma_cafe()

        elif food_type == "2":
            return choice_food_alinma_restaurant()


    elif stadium["name"] == "Aramco Stadium":

        if food_type == "1":
            return choice_food_aramco_cafe()

        elif food_type == "2":
            return choice_food_aramco_restaurant()


    else:
        return []


# King Salman Stadium - Cafes

def choice_food_king_salman_cafe():

    print("\nChoose what you're in the mood for:")

    print("1. Specialty Coffee")
    print("2. Coffee + Dessert")
    print("3. Chill & Quiet Cafe")

    while True:
        choice = input("Enter the number: ")

        if choice in ["1", "2", "3"]:
            break

        print("Please enter only 1, 2, or 3.")

    coffee_options = {
        "1": [
            "Jaqwa | Specialty Coffee",
            "Chess Specialty Coffee",
            "Puzzle Roastery"
        ],

        "2": [
            "Thoughts Express",
            "Caribou Coffee",
            "Veni"
        ],

        "3": [
            "Veni",
            "Jaqwa",
            "Right Now"
        ]
    }

    return coffee_options[choice]


# King Salman Stadium - Restaurants

def choice_food_king_salman_restaurant():

    print("\nAfter 90 minutes of cheering... we're guessing you're probably hungry now!")
    print("Let's find something delicious near King Salman Stadium.")

    print("\nWhat are you craving?")

    print("1. Saudi Food")
    print("2. Burgers")
    print("3. Indian Food")
    print("4. Mexican Food")

    while True:
        choice = input("Enter the number: ")

        if choice in ["1", "2", "3", "4"]:
            break

        print("Please enter only 1, 2, 3, or 4.")

    restaurant_options = {
        "1": [
            "Najd Village",
            "Majlah Bahraini Cuisine",
            "Al Armin"
        ],

        "2": [
            "SPREAD",
            "Al Armin",
            "Loziah"
        ],

        "3": [
            "Mr. Biryani",
            "Shalimar",
            "Shahrukh Khan"
        ],

        "4": [
            "Amigos"
        ]
    }

    return restaurant_options[choice]


# King Fahad Sports City - Cafes

def choice_food_king_fahd_cafe():

    print("\nChoose what you're in the mood for:")

    print("1. Specialty Coffee")
    print("2. Coffee + Dessert")
    print("3. Chill & Quiet Cafe")

    while True:
        choice = input("Enter the number: ")

        if choice in ["1", "2", "3"]:
            break

        print("Please enter only 1, 2, or 3.")

    coffee_options = {
        "1": [
            "Jaqwa | Specialty Coffee",
            "Chess Specialty Coffee",
            "Puzzle Roastery"
        ],

        "2": [
            "Thoughts Express",
            "Caribou Coffee",
            "Veni"
        ],

        "3": [
            "Veni",
            "Jaqwa",
            "Right Now"
        ]
    }

    return coffee_options[choice]


# King Fahad Sports City - Restaurants

def choice_food_king_fahd_restaurant():

    print("\nAfter 90 minutes of cheering... we're guessing you're probably hungry now!")
    print("Let's find something delicious near King Fahad Sports City.")

    print("\nWhat are you craving?")

    print("1. Saudi Food")
    print("2. Burgers")
    print("3. Indian Food")
    print("4. Mexican Food")

    while True:
        choice = input("Enter the number: ")

        if choice in ["1", "2", "3", "4"]:
            break

        print("Please enter only 1, 2, 3, or 4.")

    restaurant_options = {
        "1": [
            "Najed Restaurant",
            "Limonah",
            "Qasr Al Liwan"
        ],

        "2": [
            "RED . FOOD STREET",
            "Food Truck Eman",
            "Dhawq Al Aali Al Bukhari"
        ],

        "3": [
            "Hammam W Maraq",
            "Qasr Al Liwan",
            "Najed Restaurant"
        ],

        "4": [
            "Limonah",
            "RED . FOOD STREET"
        ]
    }

    return restaurant_options[choice]


# Alinma Stadium - Cafes

def choice_food_alinma_cafe():

    print("\nChoose what you're in the mood for:")

    print("1. Specialty Coffee")
    print("2. Coffee + Dessert")
    print("3. Chill & Quiet Cafe")

    while True:
        choice = input("Enter the number: ")

        if choice in ["1", "2", "3"]:
            break

        print("Please enter only 1, 2, or 3.")

    coffee_options = {
        "1": [
            "Sica Roastery",
            "Toby's Estate",
            "Cherie Cafe"
        ],

        "2": [
            "Comfy",
            "Urth",
            "Cherie Cafe"
        ],

        "3": [
            "Seventies",
            "Comfy",
            "Urth"
        ]
    }

    return coffee_options[choice]


# Alinma Stadium - Restaurants

def choice_food_alinma_restaurant():

    print("\nAfter 90 minutes of cheering... we're guessing you're probably hungry now!")
    print("Let's find something delicious near Alinma Stadium.")

    print("\nWhat are you craving?")

    print("1. Burgers")
    print("2. Saudi Food")
    print("3. Japanese / Asian Food")
    print("4. International Food")

    while True:
        choice = input("Enter the number: ")

        if choice in ["1", "2", "3", "4"]:
            break

        print("Please enter only 1, 2, 3, or 4.")

    restaurant_options = {
        "1": [
            "Burger Boutique",
            "Nevermind Burger & Shakes"
        ],

        "2": [
            "Najd Village"
        ],

        "3": [
            "Nozomi",
            "MYAZU"
        ],

        "4": [
            "Prime Cut",
            "Rudy Pizzeria"
        ]
    }

    return restaurant_options[choice]


# Aramco Stadium - Cafes

def choice_food_aramco_cafe():

    print("\nChoose what you're in the mood for:")

    print("1. Specialty Coffee")
    print("2. Coffee + Dessert")
    print("3. Chill & Quiet Cafe")

    while True:
        choice = input("Enter the number: ")

        if choice in ["1", "2", "3"]:
            break

        print("Please enter only 1, 2, or 3.")

    coffee_options = {
        "1": [
            "95 Celsius The Village",
            "Dohat Alkeef Cafe",
            "Classic Coffee"
        ],

        "2": [
            "Caribou Coffee The Village",
            "The House Cafe",
            "Funsize Brew"
        ],

        "3": [
            "Dohat Alkeef Cafe",
            "95 Celsius The Village",
            "Caribou Coffee The Village"
        ]
    }

    return coffee_options[choice]


# Aramco Stadium - Restaurants

def choice_food_aramco_restaurant():

    print("\nAfter cheering for 90 minutes... you deserve some food!")
    print("Let's find something delicious near Aramco Stadium.")

    print("\nWhat are you craving?")

    print("1. Burgers & Fast Food")
    print("2. Italian Food")
    print("3. Asian Food")
    print("4. Saudi Food")

    while True:
        choice = input("Enter the number: ")

        if choice in ["1", "2", "3", "4"]:
            break

        print("Please enter only 1, 2, 3, or 4.")

    restaurant_options = {
        "1": [
            "Texas Chicken - The Village",
            "Steak House",
            "Al Watan Burger"
        ],

        "2": [
            "Piatto Restaurant",
            "Sbarro Pizza & Pasta"
        ],

        "3": [
            "Canton",
            "Emurai Sushi"
        ],

        "4": [
            "Labani Restaurant",
            "Masoub Raafat"
        ]
    }

    return restaurant_options[choice]

"""#Person 3 - Activities"""

# Activities data based on match date

activities = {

    "June 15, 2034": [
        {
            "name": "World Cup Fan Zone",
            "time": "12:00 PM",
            "location": "Riyadh Park"
        },
        {
            "name": "Street Food Market",
            "time": "1:30 PM",
            "location": "Near King Salman Stadium"
        },
        {
            "name": "Live Music Performance",
            "time": "6:00 PM",
            "location": "Riyadh Park"
        },
        {
            "name": "Fireworks Show",
            "time": "9:30 PM",
            "location": "KAFD"
        }
    ],

    "June 16, 2034": [
        {
            "name": "Football Legends Exhibition",
            "time": "11:00 AM",
            "location": "Kingdom Arena"
        },
        {
            "name": "Fan Zone & Games",
            "time": "1:00 PM",
            "location": "Near King Fahad Sports City"
        },
        {
            "name": "Football Skills Challenge",
            "time": "5:30 PM",
            "location": "Boulevard City"
        },
        {
            "name": "Light & Drone Show",
            "time": "9:00 PM",
            "location": "Riyadh Boulevard"
        }
    ],

    "June 18, 2034": [
        {
            "name": "International Food Festival",
            "time": "1:00 PM",
            "location": "Riyadh Park"
        },
        {
            "name": "Football Freestyle Show",
            "time": "3:30 PM",
            "location": "Near King Fahad Sports City"
        },
        {
            "name": "Live DJ Performance",
            "time": "6:00 PM",
            "location": "Boulevard City"
        },
        {
            "name": "Fireworks Show",
            "time": "10:00 PM",
            "location": "KAFD"
        }
    ],

    "June 19, 2034": [
        {
            "name": "Beach Sports Festival",
            "time": "11:00 AM",
            "location": "Jeddah Waterfront"
        },
        {
            "name": "Football Skills Challenge",
            "time": "2:00 PM",
            "location": "Alinma Stadium Area"
        },
        {
            "name": "Live Band Performance",
            "time": "6:30 PM",
            "location": "Jeddah Waterfront"
        },
        {
            "name": "Water & Light Show",
            "time": "9:00 PM",
            "location": "Jeddah Waterfront"
        }
    ],

    "June 20, 2034": [
        {
            "name": "World Cup Fan Village",
            "time": "12:00 PM",
            "location": "Riyadh Park"
        },
        {
            "name": "Football Freestyle Show",
            "time": "3:00 PM",
            "location": "Boulevard City"
        },
        {
            "name": "Live DJ & Fan Celebration",
            "time": "6:00 PM",
            "location": "KAFD"
        },
        {
            "name": "Grand Fireworks Show",
            "time": "10:30 PM",
            "location": "KAFD"
        }
    ]
}


def activities_recommendation(match):

    match_date = match["date"]

    print("\n ACTIVITIES & EVENTS")
    print("=" * 40)
    print("Activities on:", match_date)

    if match_date in activities:

        for activity in activities[match_date]:
            print("\n", activity["name"])
            print(" Time:", activity["time"])
            print(" Location:", activity["location"])

        return activities[match_date]

    else:
        print("No activities available on this day.")

        return []

"""# Person 4 - Hotels"""

hotels = {

    "King Salman Stadium": [

        # Luxury
        {
            "name": "Fairmont Riyadh",
            "stars": 5,
            "category": "Luxury",
            "price_min": 700,
            "price_max": 950,
            "distance": "6.4 km",
            "minutes": 15
        },

        {
            "name": "Hilton Riyadh Hotel & Residences",
            "stars": 5,
            "category": "Luxury",
            "price_min": 650,
            "price_max": 900,
            "distance": "9.1 km",
            "minutes": 18
        },

        # Comfortable
        {
            "name": "Radisson Blu Hotel, Riyadh Qurtuba",
            "stars": 4,
            "category": "Comfortable",
            "price_min": 400,
            "price_max": 600,
            "distance": "5.3 km",
            "minutes": 12
        },

        {
            "name": "Holiday Inn Riyadh Business District",
            "stars": 4,
            "category": "Comfortable",
            "price_min": 400,
            "price_max": 550,
            "distance": "3.8 km",
            "minutes": 10
        },

        # Budget
        {
            "name": "Diamond Hotel",
            "stars": 3,
            "category": "Budget",
            "price_min": 250,
            "price_max": 350,
            "distance": "7.4 km",
            "minutes": 15
        }
    ],


    "King Fahad Sports City": [

        # Luxury
        {
            "name": "Braira Al Yarmouk",
            "stars": 5,
            "category": "Luxury",
            "price_min": 550,
            "price_max": 750,
            "distance": "4.5 km",
            "minutes": 10
        },

        # Comfortable
        {
            "name": "Al Rahden Hotel",
            "stars": 4,
            "category": "Comfortable",
            "price_min": 350,
            "price_max": 500,
            "distance": "5.7 km",
            "minutes": 12
        },

        {
            "name": "Naviti Warwick Al Yarmouk",
            "stars": 4,
            "category": "Comfortable",
            "price_min": 300,
            "price_max": 450,
            "distance": "3.9 km",
            "minutes": 10
        },

        # Budget
        {
            "name": "Tura Residence Al Khaleej",
            "stars": 3,
            "category": "Budget",
            "price_min": 150,
            "price_max": 250,
            "distance": "1.9 km",
            "minutes": 5
        },

        {
            "name": "Sunbus Hotel Service Apartments",
            "stars": 3,
            "category": "Budget",
            "price_min": 200,
            "price_max": 300,
            "distance": "1.5 km",
            "minutes": 5
        },

        {
            "name": "Boudl Gaber",
            "stars": 3,
            "category": "Budget",
            "price_min": 250,
            "price_max": 350,
            "distance": "2.2 km",
            "minutes": 6
        }
    ],

    "Alinma Stadium": [

        # Luxury
        {
            "name": "Rixos Obhur Jeddah Resort & Villas",
            "stars": 5,
            "category": "Luxury",
            "price_min": 900,
            "price_max": 1300,
            "distance": "3.9 km",
            "minutes": 10
        },

        # Comfortable
        {
            "name": "Mirada Purple Obhur",
            "stars": 4,
            "category": "Comfortable",
            "price_min": 300,
            "price_max": 450,
            "distance": "2.7 km",
            "minutes": 7
        },

        {
            "name": "Lanai Hotel",
            "stars": 4,
            "category": "Comfortable",
            "price_min": 250,
            "price_max": 400,
            "distance": "3.5 km",
            "minutes": 9
        },

        # Budget
        {
            "name": "Al Fursan United Lujen",
            "stars": 3,
            "category": "Budget",
            "price_min": 150,
            "price_max": 250,
            "distance": "1.8 km",
            "minutes": 5
        },

        {
            "name": "Al Fursan United Al Hamdaniya",
            "stars": 3,
            "category": "Budget",
            "price_min": 150,
            "price_max": 250,
            "distance": "2.4 km",
            "minutes": 6
        }
    ],

    "Aramco Stadium": [

        # Luxury
        {
            "name": "Kempinski Al Othman Hotel Al Khobar",
            "stars": 5,
            "category": "Luxury",
            "price_min": 700,
            "price_max": 950,
            "distance": "10 km",
            "minutes": 15
        },

        {
            "name": "Le Meridien Al Khobar",
            "stars": 5,
            "category": "Luxury",
            "price_min": 650,
            "price_max": 900,
            "distance": "11 km",
            "minutes": 18
        },

        # Comfortable
        {
            "name": "Holiday Inn & Suites Al Khobar",
            "stars": 4,
            "category": "Comfortable",
            "price_min": 350,
            "price_max": 500,
            "distance": "9 km",
            "minutes": 15
        },

        {
            "name": "Aloft Dhahran",
            "stars": 4,
            "category": "Comfortable",
            "price_min": 350,
            "price_max": 500,
            "distance": "10 km",
            "minutes": 17
        },

        # Budget
        {
            "name": "Ottoman Hotel Al Khobar",
            "stars": 3,
            "category": "Budget",
            "price_min": 200,
            "price_max": 300,
            "distance": "9 km",
            "minutes": 15
        }
    ],
}


def recommend_hotels(stadium):
    """
    Return hotel recommendations for the selected stadium.
    Hotels are sorted from closest to farthest.
    """

    if stadium not in hotels:
        return []

    stadium_hotels = hotels[stadium]

    # Sort hotels by distance/time from the stadium
    recommended_hotels = sorted(
        stadium_hotels,
        key=lambda hotel: hotel["minutes"]
    )

    return recommended_hotels

"""# Page Log in"""

def login():

    attempts = 3

    while attempts > 0:

        try:
            username = input("Enter your username: ")
            password = input("Enter your password: ")

            if username == "admin" and password == "12345":
                print("\nWelcome to Taktik! ⚽")
                return True

            else:
                attempts -= 1

                if attempts > 0:
                    print("Access denied.")
                    print("You have", attempts, "attempt(s) left.\n")
                else:
                    print("Access denied.")
                    print("Too many failed attempts. System locked.")

        except Exception:
            print("Something went wrong. Please try again.")

    return False

"""# Final Match-Day Plan"""

def final_plan():

    # 1. Choose stadium and match
    stadium, match = get_match_information(stadiums, matches)

    # 2. Get food recommendations
    food = food_recommendation(stadium, match)

    # 3. Get activities
    activities_list = activities_recommendation(match)

    # 4. Get hotel recommendations
    hotels_list = recommend_hotels(stadium["name"])

    # =========================
    # FINAL OUTPUT
    # =========================

    print("\n")
    print("=" * 55)
    print("⚽ TAKTIK - تكتيك")
    print("=" * 55)

    # Match Information
    print("\n🏟️ MATCH INFORMATION")
    print("-" * 35)
    print("Stadium:", stadium["name"])
    print("Match:", match["match"])
    print("Date:", match["date"])
    print("Time:", match["time"])
    print("Nearest Metro:", stadium["transport"])
    print("Area:", stadium["area"])

    # Food
    print("\n🍽️ FOOD")
    print("-" * 35)

    if food:
        for item in food:
            print("•", item)
    else:
        print("No food recommendations available.")

    # Activities
    print("\n🎉 ACTIVITIES & EVENTS")
    print("-" * 35)

    if activities_list:
        for activity in activities_list:
            print("•", activity["name"])
            print("  Time:", activity["time"])
            print("  Location:", activity["location"])
    else:
        print("No activities available on this day.")

    # Hotels
    print("\n🏨 HOTEL RECOMMENDATIONS")
    print("-" * 35)

    if hotels_list:
        for hotel in hotels_list:
            print("\n•", hotel["name"])
            print("  ⭐", hotel["stars"], "stars")
            print("  💰", hotel["price_min"], "-", hotel["price_max"], "SAR/night")
            print("  📍 Distance:", hotel["distance"])
            print("  🚗 Around", hotel["minutes"], "minutes")
            print("  🏷️ Category:", hotel["category"])
    else:
        print("No hotel recommendations available.")

    print("\nEnjoy your match-day!")
    print("Eat well. Explore more. Cheer louder!")


# =========================
# RUN THE PROGRAM
# =========================

if __name__ == "__main__":
    if login():
        final_plan()